### ISSUE TITLE
SIGABRT

### ISSUE THREAD

**Issue by tevincent** [realm/realm-kotlin#1726] opened 2024-04-18 06:56 UTC
### How frequently does the bug occur?

Sometimes

### Description

Hi there,

We have some crashes on various devices and OSes (seems to be mainly on Android 9 - 10 - 12). Is that a known issue? We don't know exactly why and how to reproduce this issue.

Thanks!

### Stacktrace & log output

```shell
OS Version: Android 10 (DOOGEE-S59-Android10-20220125)
Report Version: 104

Exception Type: Unknown (SIGABRT)

Application Specific Information:
Abort

Thread 0 Crashed:
0   libc.so                         0x78e992d1a0        abort
1   libart.so                       0x7866cc864c        art::Runtime::Abort
2   libbase.so                      0x78e9e9e650        android::base::LogMessage::~LogMessage
3   libart.so                       0x7866aaed64        art::IndirectReferenceTable::AbortIfNoCheckJNI
4   libart.so                       0x7866b8d730        <unknown> + 517119465264
5   libart.so                       0x7866d0e078        art::Thread::DecodeJObject
6   libart.so                       0x7866bee924        <unknown> + 517119863076
7   libart.so                       0x7866b991b0        <unknown> + 517119513008
8   split_config.arm64_v8a.apk      0x77fbc1e1b4        register_results_notification_cb
9   split_config.arm64_v8a.apk      0x77fbc1b928        Java_io_realm_kotlin_internal_interop_realmcJNI_register_1results_1notification_1cb
10  base.odex                       0x7800597dfc        <unknown> + 515401940476
```

### Can you reproduce the bug?

No

### Version

1.14.1

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Seems to be mostly on Android 9, 10 and 12

**Comment by rorbech** [comment] 2024-04-19 08:50
This seems to be a duplicate of #1487. I guess it wasn't fix by caching the notification callback references 🤔 

@tevincent Can you by any chance derive some additional details about when the crash is happening? 
We are not able to reproduce this, so any information that could help narrowing it would be appreciated. 
Maybe on updates or on restarts of the app? 
Or maybe some details about when your app register for notifications and potential operations triggering these?

**Comment by tevincent** [comment] 2024-04-30 06:46
We're from the same company as the author of #1487. As for the details, it's the same as #1487. Sorry for the duplicate! Maybe we can close this one and keep #1487.

**Closed** 2024-04-30 06:58 UTC
Labels: O-Community, Needs-Attention, T-Bug, SDK-Use:Local, Encryption:Off, Frequency:Sometimes, Repro:No
