### ISSUE TITLE
copyToRealm returns object with default values

### ISSUE THREAD

**Issue by shalva97** [realm/realm-kotlin#382] opened 2021-08-17 20:10 UTC
okay so this is really weird behavior or im too tired, but anyway I have a test and its failing so here it is

```
import androidx.test.ext.junit.runners.AndroidJUnit4
import io.realm.Realm
import io.realm.RealmConfiguration
import io.realm.RealmObject
import io.realm.delete
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class RepoTest {

    class Task : RealmObject {
        var name: String = "new task"
        var status: String = "Open"

        fun toAnotherTask(): AnotherTask {
            return AnotherTask(name, status)
        }
    }

    data class AnotherTask(
        val name: String,
        var status: String
    )

    class TaskRepository {

        private val config = RealmConfiguration(schema = setOf(Task::class))
        private val realm = Realm(config)

        init {
            realm.writeBlocking {
                objects(Task::class).delete()
            }
        }

        fun getAll(): List<Task> {
            return realm.objects(Task::class)
        }

        fun addTask(task: Task): AnotherTask {
            return realm.writeBlocking {
                copyToRealm(task)
                    .toAnotherTask()
            }
        }

        fun deleteTask(task: Task) {
            realm.writeBlocking {
                findLatest(task)?.delete() // this works
            }
        }
    }

    private val myRepo = TaskRepository()


    @Test
    fun testRepo() {
        val myTask = Task().apply {
            name = "old task"
        }

        val mySavedTask = myRepo.addTask(myTask)

        assert(mySavedTask.name == "old task")

    }

}
```

I have changed `name` to "old task" for the myTask variable, so I expect mySavedTask's name property to be also "old task".
addTask directly maps returned object to AnotherTask, I dont get it why but at the moment it gets mapped `Task` object has default values. 

Why would it still have default values?

**Comment by rorbech** [comment] 2021-08-18 06:41
Looks like a duplicate of #375, where other methods somehow uses the wrong getter for the field. Will have to investigate.

**Comment by shalva97** [comment] 2021-08-18 14:49
found the workaround, mapping the objects with extension functions work correctly

```
    fun Task.toAnotherTask(): AnotherTask {
        return AnotherTask(name, status)
    }
    
```

**Comment by rorbech** [comment] 2021-08-18 14:52
Yes, anything that uses accessors from outside the scope of the class seems to work. It seems to be a JVM IR backend error in the compiler, as it isn't failing on macos.

**Comment by rorbech** [comment] 2021-08-19 08:43
Closing as duplicate of #375

**Closed by rorbech** 2021-08-19 08:43 UTC
Labels: O-Community
