### ISSUE TITLE
[RLM_ERR_NO_SUCH_OBJECT]: Key 'X' not found in <classname> when nullifying incoming links

### ISSUE THREAD

**Issue by thiagodelgado111** [realm/realm-kotlin#1537] opened 2023-10-04 19:27 UTC
### How frequently does the bug occur?

Sometimes

### Description

Hi folks!

Has anyone seen this one before? It looks like it happens when trying to create an asymmetric object using insert and it might be related to realm-core (https://github.com/realm/realm-core/blob/8948e8399b93f8e3bcf3b914f1f1cf4c2a5a6a6b/src/realm/cluster.cpp#L974). I couldn't reproduce it so maybe you can give me a hand figuring this one out?

Another thing I noticed is that the error message says it couldn't find Key '4' in my AsymmetricRealmObject but my primary key is an ObjectId and I'm not using dictionaries or embedded models.

### Stacktrace & log output

```shell
java.lang.IllegalArgumentException: [RLM_ERR_NO_SUCH_OBJECT]: Key '4' not found in 'Event' when nullifying incoming links
    at io.realm.kotlin.internal.interop.CoreErrorConverter.asThrowable
    at io.realm.kotlin.internal.interop.CoreErrorConverter.asThrowable
    at io.realm.kotlin.internal.interop.realmcJNI.realm_commit(SourceFile)
    at io.realm.kotlin.internal.SuspendableWriter$WriterRealm.getRealmReference
    at io.realm.kotlin.internal.WriteTransactionManager$DefaultImpls.commitTransaction
    at io.realm.kotlin.internal.SuspendableWriter$WriterRealm.commitTransaction
    at io.realm.kotlin.internal.interop.realmc.realm_commit
    at io.realm.kotlin.internal.interop.RealmInterop.realm_commit
    at io.realm.kotlin.internal.WriteTransactionManager$DefaultImpls.commitTransaction
    at io.realm.kotlin.internal.SuspendableWriter$WriterRealm.commitTransaction
    at io.realm.kotlin.internal.SuspendableWriter$write$2.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith
    at kotlinx.coroutines.DispatchedTask.run
    at kotlinx.coroutines.DispatchedTask.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)
```

### Can you reproduce the bug?

No

### Version

1.10.0

### What Atlas App Services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

Android 

### Build environment

Android Studio version: Iguana | 2023.2.1 Canary 6
Android Build Tools version: 33.0.2
Gradle version: 8.0.2

**Comment by cmelchior** [comment] 2023-10-11 18:35
Key '4' is our internal ID used for Objects, which is probably why you don't recognize it. 

Asymmetric objects are deleted on the device once they are sent to the server and it looks like something is going wrong there for some reason.

Can you share the schemas used for these objects?

**Comment by jedelbo** [comment] 2023-10-16 08:17
Internal note: related Core version is .13.15.2

**Comment by jedelbo** [comment] 2023-10-16 11:03
I can reproduce the error, if I delete the just created object before the transaction is committed. Could that be the issue here?

**Closed** 2023-10-20 07:03 UTC
Labels: O-Community, T-Bug
