### ISSUE TITLE
Realm Kotlin MultiPlatform Sync in jvmApp on Windows

### ISSUE THREAD

**Issue by JRWilding** [realm/realm-kotlin#655] opened 2022-01-26 23:30 UTC
#### Expected results

Can open a synced Realm database without crashing the app

#### Actual Results

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
C:\jenkins\workspace\realm_realm-kotlin_releases\packages\external\core\src\realm\object-store\util\scheduler.cpp:99: [realm-core-11.6.1] No built-in scheduler implementation for this platform. Register your own with Scheduler::set_default_factory()
<backtrace not supported on this platform>!!! IMPORTANT: Please report this at https://github.com/realm/realm-core/issues/new/choose

Execution failed for task ':jvmApp:run'.

#### Steps & Code to Reproduce
Clone https://github.com/realm/realm-kotlin-samples
execute the Realm Kotlin Multiplatform Demo's `:jvmApp:run` gradle task
crashes on app startup when trying to open Realm `CounterRepository:57`

if you open Realm using a `RealmConfiguration` instead of a `SyncConfiguration` to use a local realm instance, it works.
probably more of an issue for the realm-kotlin project, but the crash reports specifically instructs to report here.

#### Core version
Core version: whatever version realm kotlin 0.8.2 uses

**Comment by nhachicha** [comment] 2022-01-27 01:16
Hi @JRWilding thanks for reporting this issue, I transferred it here since it's more appropriate. 
I'm able to reproduce this on Linux and Windows we'll try to fix it soon.

**Comment by nhachicha** [comment] 2022-01-28 22:03
@JRWilding this was fixed in `0.9.0`

**Closed by nhachicha** 2022-01-28 22:03 UTC
Labels: O-Community
