### ISSUE TITLE
Query fails with list passed as query argument

### ISSUE THREAD

**Issue by promanowicz** [realm/realm-kotlin#1414] opened 2023-06-07 14:39 UTC
### How frequently does the bug occur?
Always

### Description
The following query

val idList = listOf(1L, 2L)
realm.query(Foo::class, "id IN $0", idList).find()

Results with exception

If I place the list as string in the parameter then it works.

val idListString = idList.joinToString(", ")

realm.query(Leaf::class, "id IN { $idListString} ", null ).find()

### Stacktrace & log output
```shell
java.lang.IllegalArgumentException: Cannot use object of type val kotlin.reflect.KClass<T>.simpleName: kotlin.String? as query argument
at io.realm.kotlin.internal.RealmValueArgumentConverter.convertArg-399rIkc(Converters.kt:347)
at io.realm.kotlin.internal.RealmValueArgumentConverter.convertToQueryArgs(Converters.kt:357)
at io.realm.kotlin.internal.query.ObjectQuery$Companion.parseQuery-6CC_B8E(ObjectQuery.kt:195)
at io.realm.kotlin.internal.query.ObjectQuery$Companion.access$parseQuery-6CC_B8E(ObjectQuery.kt:188)
at io.realm.kotlin.internal.query.ObjectQuery.<init>(ObjectQuery.kt:71)
at io.realm.kotlin.internal.query.ObjectQuery.<init>(Unknown Source:0)
at io.realm.kotlin.internal.InternalTypedRealm$DefaultImpls.query(InternalTypedRealm.kt:57)
at io.realm.kotlin.internal.SuspendableWriter$WriterRealm.query(SuspendableWriter.kt:57)
...
```

### Can you reproduce the bug?
Always

### Reproduction Steps
val idListString = idList.joinToString(", ")

val tests = realm.query(Leaf::class, "id IN { $idListString} ", null ).find()

### Version
1.9.0

### What Atlas App Services are you using?
Local Database only

### Are you using encryption?
No

### Platform OS and version(s)
Android 13

### Build environment
Android Studio version: 2022.2.1 Patch 2
Android Build Tools version: 33
Gradle version: 7.5

**Comment by rorbech** [comment] 2023-06-07 19:40
This seems to be a duplicate of https://github.com/realm/realm-kotlin/issues/929

**Closed as completed** 2023-06-07 19:41 UTC
Labels: T-Bug, O-Community, Frequency:Always, Repro:Always, SDK-Use:Local, Encryption:Off
