### ISSUE TITLE
Sync doesn't seem to load all data initially on a new build on IOS

### ISSUE THREAD

**Issue by iamsteveholmes** [realm/realm-kotlin#820] opened 2022-05-01 16:45 UTC
A number of my collections come up blank when the app is started the first time on a device (or emulator).  In this case I'm doing simple queries that pull everything of a particular type from realm.  I can leave the page and come back forcing a new query but still the data is blank.  When I shut down the app (or it crashes) and come and re-open it then the data appears.  

When I open an app for the first time I can see a message like this in the sync logs:
```
[
  "Client bootstrap completed in 10.126345ms. Received 1 download(s) containing 25 changeset(s) (30.8 kB total)."
]
```

But I still am not getting all the data.

Sometimes some data is there for some objects but not for others.  It makes me wonder if this is some sort of Changeset or schema version issue.

Also, the logs will sometime show an update to realm when the app is restarted,  I don't understand exactly what that means but I assume realm is updating to a new Changeset?

My workaround is:

```
val realm: Realm = Realm.open(config)

    init {
        runBlocking {
            realm.syncSession.downloadAllServerChanges()
        }
    }
```

I'm not sure why that isn't the default but it does seem to give me all my data.

**Comment by cmelchior** [comment] 2022-05-02 06:02
Hmm, that sounds a bit weird, but if your data is appearing after an app restart I would mostly think it is a race condition with how data is loaded and how you fetch data.

How it works under the hood is that Realm downloads data in the background, i.e. it isn't immediately available once you call `Realm.open()`. This is by design, so it also works when offline.

This is also why you can use `realm.syncSession.downloadAllServerChanges()` as a way to "force" the download and we should also add `SyncConfiguration.waitForInitialRemoteData()` (similar to Realm Java) which should make this easier.

My guess, as to why data doesn't show up is then that you are fetching data using `query.find()` instead of `query.asFlow()`? If you use the flow variant, even if data isn't there in beginning you will get notified when it arrives, and this would also be the way you generally support apps that are responsive to changes from other devices.

If none of the above seems to fit your code, we probably need a small sample project to be able to figure out what is wrong.

**Comment by iamsteveholmes** [comment] 2022-05-03 16:41
@cmelchior That checks with what I'm experiencing to some extent.  I had some legacy code that was not using flows while most of my queries are using flows.  The ones that didn't never seemed to update even when re-querying.  In my case I'm using find().asFlow for my flows instead of query<>.asFlow().  They appear to return the same Flow<ResultsChange<?>>.  Could that be causing me issues?

**Comment by cmelchior** [comment] 2022-05-03 19:09
If that is a query for a single object, then yes, there is a difference:

- If you do `realm.query<Person>("id = 42").find().asFlow()`, it will run the query and then attach the Flow to _that_ object and that object alone, i.e. if the object is deleted the flow is terminated. This flow returns `ObjectChange` objects. 

- If you do `realm.query<Person>("id = 42").asFlow()`, the Flow is on the "query" itself, meaning that you might get different objects, i.e. the flow never terminates and can return `null` if no objects match. This flow returns `SingleQueryChange` objects.

It is a bit tricky, but there are use cases for both. We did try to explain the difference in the docs, but it sounds like we could improve that.

**Comment by iamsteveholmes** [comment] 2022-05-03 19:38
@cmelchior Looking through my code it appears for single objects I'm running `query<>("_id = $0", id).first().asFlow()`.

In my use case I'm only using flows to pull an entire collection/all objects of a given type.  I appear to be mixing `query<>.find().asFlow()` and `query<>.asFlow()`.  Am I wrong thinking that in those cases the results are the same but `find()` is extraneous.

**Comment by cmelchior** [comment] 2022-05-03 19:51
Yes, using `find().asFlow()` is usually just extra work for no reason, it also runs the first query on the calling thread, usually the UI thread, which can be pretty bad.

**Comment by iamsteveholmes** [comment] 2022-05-04 15:58
@cmelchior Thanks I appreciate the help.

**Comment by rorbech** [comment] 2022-06-28 14:12
Closing this assuming that it is fully answered. Feel free to add additional comments if this is not the case.

**Closed** 2022-06-28 14:13 UTC
Labels: O-Community
