### ISSUE TITLE
Please use language version 1.9 or below ?

### ISSUE THREAD

**Issue by techker** [realm/realm-kotlin#1647] opened 2024-01-31 18:03 UTC
### How frequently does the bug occur?
Always

### Description
Hello, Updated my project and now i get this message?

There are some plugins incompatible with language version 2.0:
  io.realm.kotlin.compiler.Registrar
Please use language version 1.9 or below

```
Gradle setup :
    id 'com.android.application' version '8.1.2' apply false
    id 'com.android.library' version '8.1.2' apply false
    id "com.google.protobuf" version "0.9.4" apply false
    id("com.google.dagger.hilt.android") version "2.46.1" apply false
    id("org.jetbrains.kotlin.plugin.parcelize") version "2.0.0-Beta3" apply false
    id 'org.jetbrains.kotlin.android' version '1.9.20' apply false
    id 'org.jetbrains.kotlin.plugin.serialization' version '1.7.10' apply false
    id("com.google.gms.google-services") version "4.3.15" apply false
    id("com.google.firebase.crashlytics") version "2.9.6" apply false
    id ("io.realm.kotlin" )version '1.13.0' apply false
    id("com.google.devtools.ksp") version "2.0.0-Beta3-1.0.17" apply false
```

In gradle 
plugins {
   id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'io.realm.kotlin'
    id 'dagger.hilt.android.plugin'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
}

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

### Stacktrace & log output
```shell
There are some plugins incompatible with language version 2.0:
  io.realm.kotlin.compiler.Registrar
Please use language version 1.9 or below
```

### Can you reproduce the bug?
Always

### Version
8.1.2

### What Atlas App Services are you using?
Local Database only

### Are you using encryption?
No

### Platform OS and version(s)
12

### Build environment
Android Studio Jellyfish | 2023.3.1 Canary 7
Build #AI-233.13135.103.2331.11360849, built on January 25, 2024
Runtime version: 17.0.9+0-17.0.9b1087.9-11255266 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 8
Metal Rendering is ON
Registry:
  ide.instant.shutdown=false
  ide.experimental.ui=true

**Comment by nirinchev** [comment] 2024-01-31 19:08
This is a duplicate of https://github.com/realm/realm-kotlin/issues/1614.

**Closed by nirinchev** 2024-01-31 19:08 UTC
Labels: O-Community, T-Bug, Frequency:Always, Repro:Always, SDK-Use:Local, Encryption:Off
