### ISSUE TITLE
Method getLooper in android.os.HandlerThread not mocked

### ISSUE THREAD

**Issue by shalva97** [realm/realm-kotlin#381] opened 2021-08-17 19:49 UTC
Trying to run a test localy throws RuntimeException
![image](https://user-images.githubusercontent.com/22417494/129790777-cbe31360-e4ba-4532-9478-ac411099311c.png)

**Comment by iamsteveholmes** [comment] 2021-08-17 22:06
I also experienced this issue.  It happened when I was running the tests in  `commonTest`.  The tests ran fine under `iosTest`.

**Comment by cmelchior** [comment] 2021-08-18 06:30
This happens when you try to run the tests as pure JVM tests. We only support Android right now on the JVM. Pure JVM support is coming but is tracked here: #62. 

Closing as duplicate of #62

**Closed by cmelchior** 2021-08-18 06:30 UTC
Labels: O-Community

**Comment by rorbech** [comment] 2021-08-18 06:34
Just to clarify. Executing `commonTest` on the Android targets is currently not running the tests as instrumentation test but as jvm unit test. You can track https://youtrack.jetbrains.com/issue/KT-46452.
