### ISSUE TITLE
Realm SDK Native crash (SIGSEGV, librealmc.so, invoke_core_notify_callback)

### ISSUE THREAD

**Issue by jhonnyinstacart** [realm/realm-kotlin#1603] opened 2023-12-12 23:04 UTC
### How frequently does the bug occur?

Sometimes

### Description

We have recently migrated some of our local databases from the java SDK to the kotlin SDK, we have noted a native crash on our Crashlytics reports and it points to the realm kotlin SDK, at least from what I can tell. Find the stacktrace from Crashlytics and logcat below.

Note that we do use atlas sync service in our app but that database is not migrated to kotlin SDK yet and since the trace points to kotlin then I'm assuming this is related to one of the kotlin SDK databases.

### Stacktrace & log output

```shell
// Crashlytics report:
Crashed: Thread: SIGSEGV  0x000000000000002a
#00 pc 0x9644c7 librealmc.so (std::__ndk1::__shared_ptr_pointer<char*, std::__ndk1::default_delete<char []>, std::__ndk1::allocator<char> >::__on_zero_shared_weak()) (BuildId: 2e2c36a1aa05d20044fdc0dda7f8f7b122174e5a)
#01 pc 0x2bf126 librealmc.so (std::__ndk1::__shared_ptr_pointer<char*, std::__ndk1::default_delete<char []>, std::__ndk1::allocator<char> >::__on_zero_shared_weak()) (BuildId: 2e2c36a1aa05d20044fdc0dda7f8f7b122174e5a)
#02 pc 0x296e21 librealmc.so (invoke_core_notify_callback(long long)) (BuildId: 2e2c36a1aa05d20044fdc0dda7f8f7b122174e5a)
#03 pc 0x293dc4 librealmc.so (Java_io_realm_kotlin_internal_interop_realmcJNI_invoke_1core_1notify_1callback) (BuildId: 2e2c36a1aa05d20044fdc0dda7f8f7b122174e5a)
#04 pc 0x144f68 libart.so (BuildId: 26b0fc8885e87fc8f11e1081b83a9b8e)

// Logcat trace:
12-05 10:48:20.378  4232 11903 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x65766974616e2c in tid 11903 (notifier-featur), pid 4232 (deserteagle.dev)
12-05 10:48:20.590 11912 11912 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-05 10:48:20.590 11912 11912 F DEBUG   : Revision: '0'
12-05 10:48:20.590 11912 11912 F DEBUG   : ABI: 'arm64'
12-05 10:48:20.591 11912 11912 F DEBUG   : Timestamp: 2023-12-05 10:48:20-0500
12-05 10:48:20.591 11912 11912 F DEBUG   : pid: 4232, tid: 11903, name: notifier-featur  >>> com.queuehop.deserteagle.dev <<<
12-05 10:48:20.591 11912 11912 F DEBUG   : uid: 10096
12-05 10:48:20.591 11912 11912 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x65766974616e2c
12-05 10:48:20.591 11912 11912 F DEBUG   :     x0  0000007dc45eac80  x1  0000007df2c65c40  x2  0000007df2c5e518  x3  0000000000000000
12-05 10:48:20.591 11912 11912 F DEBUG   :     x4  000000006fb7e770  x5  0000000015f17d08  x6  00000000147f3480  x7  000000009bc58140
12-05 10:48:20.591 11912 11912 F DEBUG   :     x8  0000007dc45eac80  x9  2065766974616e3c  x10 0000000000430000  x11 0000000000000005
12-05 10:48:20.591 11912 11912 F DEBUG   :     x12 0000007e06625738  x13 0000007e795364f0  x14 0000007e79536550  x15 0000000000000000
12-05 10:48:20.591 11912 11912 F DEBUG   :     x16 0000007df2cde8b0  x17 0000007df270dab0  x18 0000007df419a000  x19 0000007d34214c00
12-05 10:48:20.591 11912 11912 F DEBUG   :     x20 0000007e06627020  x21 0000007d34214c00  x22 0000007e06625a30  x23 0000007e0bae6824
12-05 10:48:20.591 11912 11912 F DEBUG   :     x24 0000000000000008  x25 0000007e06627020  x26 0000007d34214cb0  x27 0000000000000002
12-05 10:48:20.591 11912 11912 F DEBUG   :     x28 0000007e066257c0  x29 0000007e06625770
12-05 10:48:20.591 11912 11912 F DEBUG   :     sp  0000007e06625710  lr  0000007df272e628  pc  0000007df2c55534
12-05 10:48:20.602 11912 11912 F DEBUG   : 
12-05 10:48:20.602 11912 11912 F DEBUG   : backtrace:
12-05 10:48:20.602 11912 11912 F DEBUG   :       #00 pc 0000000000846534  /data/app/com.queuehop.deserteagle.dev-FkGDRmVGsffUEEIknmKYEA==/base.apk!librealmc.so (offset 0x4ef0000) (BuildId: aa6e02b9a2f0043624262102d3146bd74c01dd87)
12-05 10:48:20.602 11912 11912 F DEBUG   :       #01 pc 000000000031f624  /data/app/com.queuehop.deserteagle.dev-FkGDRmVGsffUEEIknmKYEA==/base.apk!librealmc.so (offset 0x4ef0000) (BuildId: aa6e02b9a2f0043624262102d3146bd74c01dd87)
```

### Can you reproduce the bug?

No

### Reproduction Steps

We are working on trying to come up with repro steps.

### Version

1.12.0

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android 10

### Build environment

Android Studio version: Android Studio Iguana | 2023.2.1 Canary 10
Android Build Tools version: 33.0.2
Gradle version: 7.6.2

**Comment by rorbech** [comment] 2023-12-13 07:27
This looks like a duplicate of https://github.com/realm/realm-kotlin/issues/1543, which is fixed in [`1.13.0`](https://github.com/realm/realm-kotlin/blob/main/CHANGELOG.md#1130-2023-12-01). I will close as a duplicate for now. Please get back if you observe anything similar with newer releases.

**Closed by rorbech** 2023-12-13 07:27 UTC
Labels: O-Community, T-Bug, SDK-Use:Local, Encryption:Off, Frequency:Sometimes, Repro:No

**Comment by jhonnyinstacart** [comment] 2023-12-13 15:43
This issue doesn't look like #1543, as I mentioned in the description my issue doesn't relate to atlas sync (at least from the logs we were able to gather), #1543 is directly related to it. Do you mind taking another look? 🙏 @rorbech

**Comment by rorbech** [comment] 2023-12-13 16:08
Hi @jhonnyinstacart. The referenced issue is not specifically related to sync. It was just appearing in our sync integration tests due to timing of these use cases. 

The referenced issue a "crash when notifying on a released scheduler" which is exactly what your the `invoke_core_notify_callback` entry from your stack trace indicates.
