### ISSUE TITLE
Kotlin data class support

### ISSUE THREAD

**Issue by Burtan** [realm/realm-kotlin#946] opened 2022-07-31 17:39 UTC
Hi,
are there any plans to support data classes? Not being able to have immutable fields on RealmObjects is a big restrictions!
Thanks!

**Comment by cmelchior** [comment] 2022-08-02 07:11
Hi @Burtan 

We are probably not going to support model classes as data classes as the data in Realm is inherently mutable, but we have talked about support _projections_, which represent a read-only view of the data. In that case, exposing it as immutable data classes would be natural. You can read more here: https://github.com/realm/realm-kotlin/issues/947

**Comment by cmelchior** [comment] 2022-08-02 07:11
Closing as duplicate of #947

**Closed by cmelchior** 2022-08-02 07:11 UTC
Labels: O-Community
