### ISSUE TITLE
Credentials.anonymous(reuseExisting = true) not work

### ISSUE THREAD

**Issue by helmysaeed** [realm/realm-kotlin#1747] opened 2024-05-18 12:16 UTC
### How frequently does the bug occur?

Always

### Description

Expected results
use the same anonymous user ID with every session

Actual Results
every time I log in with the anonymous user Realm generates a new user with a different ID so I can not trace the user

### Can you reproduce the bug?

Always

### Reproduction Steps

var app by mutableStateOf( App.create("appid"))

val anonymousCredentials = Credentials.anonymous(reuseExisting = true)
user = app.login(anonymousCredentials)
println("userId"+user!!.id)

### Version

kotlin SDK 1.16.0

### What Atlas App Services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

windows 10

### Build environment

Android Studio version: ...
Android Build Tools version: ...
Gradle version: ...

**Comment by nirinchev** [comment] 2024-05-21 09:43
This is a duplicate of https://github.com/realm/realm-core/issues/7709.

**Closed by nirinchev** 2024-05-21 09:43 UTC
Labels: O-Community, T-Bug
