### ISSUE TITLE
Iterating live result during update (write) is slow

### ISSUE THREAD

**Issue by konnovdev** [realm/realm-kotlin#886] opened 2022-06-12 16:21 UTC
## Problem
Perfoming the following operations:
`Given a dataset of 1000 elements, update matching string with a new string`
**Takes** a ridiculously **huge** **amount time**
And the time complexity grows dramatically when increasing the dataset to 10 000 elements

## Code snippet
```
    override suspend fun update(param: String, objectToInsert: NewsReportDto) {
        realm.query<NewsReportDto>("title == $0", param)
            .find()
            .forEach { oldNewsReportDto ->
                realm.write {
                    findLatest(oldNewsReportDto)?.apply {
                        title = objectToInsert.title
                        description = objectToInsert.description
                    }
                }
            }
    }
```
[Link to this **update** method source code](https://github.com/konnovdev/android_databases/blob/master/feature/realm/src/main/java/dev/konnov/feature/realm/data/datasource/NewsDbDataSource.kt)
[Link to the data generator](https://github.com/konnovdev/android_databases/blob/master/common/dataset/news-reports/src/main/java/dev/konnov/common/dataset/newsreports/data/datasource/NewsReportDataSetDataSource.kt)

## Performance result
<img width="400" alt="performance screenshot" src="https://user-images.githubusercontent.com/49668442/173242664-b425bac8-9b64-4c38-9e2a-d899169af8f9.png">

Let me know if i'm doing something wrong, the corresponding [update query for **Room**](https://github.com/konnovdev/android_databases/blob/master/feature/room/src/main/java/dev/konnov/feature/room/data/database/NewsReportDao.kt) 
```
        "UPDATE newsReport " +
                "SET title = :newTitle," +
                "description = :newDescription " +
                "WHERE title = :title"
```
takes very little time for example, 20 miliseconds for 1k elements, and 20 miliseconds for 10k elements

**Comment by rorbech** [comment] 2022-06-13 06:45
Hi @konnovdev. Thanks for the report. I am currently investigating a memory leak in the JVM/Native transition. I will see if I can replicate your observations and investigate if it is related.

**Comment by nirinchev** [comment] 2022-06-13 07:15
One thing to note is that you seem to be doing 10k writes rather than 1 write updating 10k elements. This is significantly different from the Room query.

**Comment by rorbech** [comment] 2022-06-13 07:18
But the tests for doubles uses the same approach, so seems like the issue is in fact related specifically to strings.

**Comment by konnovdev** [comment] 2022-06-13 08:51
@nirinchev oh, is there a way to make 10k updates in one operation?

**Comment by konnovdev** [comment] 2022-06-13 08:53
@rorbech with the test on real numbers - actually it's 99.9% unique numbers, so in that case there will be just a few rows updated, whereas in the test of strings it's 0.01% unique strings

**Comment by rorbech** [comment] 2022-06-13 09:01
@konnovdev Ahh, ok, then I guess the amount of transactions is probably the cause. You can just do the query inside the write instead. Then you are also doing the query on the latest version of the realm and you can skip the `findLatest`.
```
realm.write {
    query<NewsReportDto>("title == $0", param)
       .find()
      .forEach { oldNewsReportDto ->
         oldNewsReportDto.apply {
             ....
         }
       }
    }
```

**Comment by konnovdev** [comment] 2022-06-13 10:04
@rorbech it says I cannot skip the **findlatest** step
```
    java.lang.IllegalStateException: Cannot set `NewsReportDto.$title` to `not strange`: changing Realm data can only be done on a live object from inside a write transaction. Frozen objects can be turned into live using the 'MutableRealm.findLatest(obj)' API.
```

But moving **realm.write** like this does the trick indeed! Now update for **1k** items takes **19 milliseconds**, and update for **10k** items **121 milliseconds**.

Here is the code snippet:
```
        realm.write {
            realm.query<NewsReportDto>("title == $0", param)
                .find()
                .forEach { oldNewsReportDto ->
                    findLatest(oldNewsReportDto)?.apply {
                        this.apply {
                            title = objectToInsert.title
                            description = objectToInsert.description
                        }
                    }
                }
        }
```

**Comment by konnovdev** [comment] 2022-06-13 10:05
Btw I think **bulk update** could be a good addition to the documentation in **Readme.md** ))

**Comment by rorbech** [comment] 2022-06-13 10:10
@konnovdev Great. 

Regarding `findLatest`: You have to do the query against the mutable realm (the receiver of the `write`) which is referencing the latest version of the realm and not against `realm`. So 
```
realm.query<NewsReportDto>("title == $0", param)
```
should just be 
```
query<NewsReportDto>("title == $0", param)
```
instead and then you should be able to skip the `findLatest`.

**Comment by konnovdev** [comment] 2022-06-13 10:21
Strange, when I don't use **findLatest**, it's 10 times slower.
So doing this:
```
        realm.write {
            query<NewsReportDto>("title == $0", param)
                .find()
                .forEach { oldNewsReportDto ->
                    oldNewsReportDto.apply {
                        title = objectToInsert.title
                        description = objectToInsert.description
                    }
                }
        }
```
Takes 10 times more time than this
```
        realm.write {
            realm.query<NewsReportDto>("title == $0", param)
                .find()
                .forEach { oldNewsReportDto ->
                    findLatest(oldNewsReportDto)?.apply {
                        title = objectToInsert.title
                        description = objectToInsert.description
                    }
                }
        }
```

**Comment by rorbech** [comment] 2022-06-13 11:41
@konnovdev I have been digging a bit and what happens is that the underlying query is most likely re-run when you update the  objects, so for now the best thing is probably to iterate the stable result from the frozen `realm.query`. I will have to dig a bit further to understand the details and, if the hypothesis is right, the options of providing a stable results for these use cases.

**Comment by rorbech** [comment] 2022-06-28 15:15
Closing this issue as the various root causes of the lower speed has been explained, but created #914 to enhance the API to provide a stable result for fast and predictable iteration.

**Closed by rorbech** 2022-06-28 15:15 UTC
Labels: O-Community, Needs-Attention
