### ISSUE TITLE
SIGABRT : Java_io_realm_kotlin_internal_interop_realmcJNI_realm_1list_1size

### ISSUE THREAD

**Issue by Shabinder** [realm/realm-kotlin#1576] opened 2023-11-20 12:42 UTC
### How frequently does the bug occur?

Sometimes

### Description

We are seeing following crashes reported on our Android App _(distributed via playstore)_

SIGABRT: **[split_config.arm64_v8a.apk!librealmc.so] Java_io_realm_kotlin_internal_interop_realmcJNI_realm_1list_1size**

Some devices which are inflicted:
 - vivo 2111
 - OnePlus OnePlusNordCE
 - POCO karna

### Stacktrace & log output

```shell
[split_config.arm64_v8a.apk!librealmc.so] Java_io_realm_kotlin_internal_interop_realmcJNI_realm_1list_1size

Pure virtual function called!


backtrace:
  #00  pc 0x000000000007da34  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168)
  #01  pc 0x000000000083c954  /data/app/~~zS5ObOwx2IORomtK9QptyA==/com.subconscious.thrive-gdKchnn34ILGvF2CofgXCg==/split_config.arm64_v8a.apk!librealmc.so (BuildId: 533e53c62871f9d2818ed137fd0c02c6241c7609)
  #02  pc 0x000000000083dab8  /data/app/~~zS5ObOwx2IORomtK9QptyA==/com.subconscious.thrive-gdKchnn34ILGvF2CofgXCg==/split_config.arm64_v8a.apk!librealmc.so (BuildId: 533e53c62871f9d2818ed137fd0c02c6241c7609)
  #03  pc 0x0000000000564e6c  /data/app/~~zS5ObOwx2IORomtK9QptyA==/com.subconscious.thrive-gdKchnn34ILGvF2CofgXCg==/split_config.arm64_v8a.apk!librealmc.so (BuildId: 533e53c62871f9d2818ed137fd0c02c6241c7609)
  #04  pc 0x000000000036cb64  /data/app/~~zS5ObOwx2IORomtK9QptyA==/com.subconscious.thrive-gdKchnn34ILGvF2CofgXCg==/split_config.arm64_v8a.apk!librealmc.so (BuildId: 533e53c62871f9d2818ed137fd0c02c6241c7609)
  #05  pc 0x00000000005bc4d4  /data/app/~~zS5ObOwx2IORomtK9QptyA==/com.subconscious.thrive-gdKchnn34ILGvF2CofgXCg==/split_config.arm64_v8a.apk!librealmc.so (BuildId: 533e53c62871f9d2818ed137fd0c02c6241c7609)
  #06  pc 0x00000000005bba48  /data/app/~~zS5ObOwx2IORomtK9QptyA==/com.subconscious.thrive-gdKchnn34ILGvF2CofgXCg==/split_config.arm64_v8a.apk!librealmc.so (BuildId: 533e53c62871f9d2818ed137fd0c02c6241c7609)
  #07  pc 0x00000000005baf30  /data/app/~~zS5ObOwx2IORomtK9QptyA==/com.subconscious.thrive-gdKchnn34ILGvF2CofgXCg==/split_config.arm64_v8a.apk!librealmc.so (BuildId: 533e53c62871f9d2818ed137fd0c02c6241c7609)
  #08  pc 0x0000000000313364  /data/app/~~zS5ObOwx2IORomtK9QptyA==/com.subconscious.thrive-gdKchnn34ILGvF2CofgXCg==/split_config.arm64_v8a.apk!librealmc.so (BuildId: 533e53c62871f9d2818ed137fd0c02c6241c7609)
  #09  pc 0x00000000002eab9c  /data/app/~~zS5ObOwx2IORomtK9QptyA==/com.subconscious.thrive-gdKchnn34ILGvF2CofgXCg==/split_config.arm64_v8a.apk!librealmc.so (Java_io_realm_kotlin_internal_interop_realmcJNI_realm_1list_1size+80) (BuildId: 533e53c62871f9d2818ed137fd0c02c6241c7609)
  #10  pc 0x000000000034aa30  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+144)
  #11  pc 0x00000000005bc59c  /apex/com.android.art/lib64/libart.so (nterp_helper+1948)
  #12  pc 0x0000000001730a8c  /data/app/~~zS5ObOwx2IORomtK9QptyA==/com.subconscious.thrive-gdKchnn34ILGvF2CofgXCg==/oat/arm64/base.vdex (io.realm.kotlin.internal.ManagedRealmList.U+60)
  #13  pc 0x00000000005bcd54  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
  #14  pc 0x0000000001787f20  /data/app/~~zS5ObOwx2IORomtK9QptyA==/com.subconscious.thrive-gdKchnn34ILGvF2CofgXCg==/oat/arm64/base.vdex (kotlin.collections.AbstractMutableList.size)
  #15  pc 0x0000000000479f9c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.util.AbstractList$Itr.hasNext+60)
  #16  pc 0x000000000051a744  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.util.AbstractCollection.toString+84)
  #17  pc 0x00000000004e85a8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.lang.StringBuilder.append+72)
  #18  pc 0x00000000005bcdb0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016)
  #19  pc 0x00000000014ce072  /data/app/~~zS5ObOwx2IORomtK9QptyA==/com.subconscious.thrive-gdKchnn34ILGvF2CofgXCg==/oat/arm64/base.vdex (com.subconscious.thrive.models.cohort.CohortModel.toString+66)
  #20  pc 0x00000000004e85a8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.lang.StringBuilder.append+72)
  #21  pc 0x000000000051a7e4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.util.AbstractCollection.toString+244)
  #22  pc 0x00000000004e85a8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.lang.StringBuilder.append+72)
  #23  pc 0x00000000005bcdb0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016)
  #24  pc 0x000000000136f0e6  /data/app/~~zS5ObOwx2IORomtK9QptyA==/com.subconscious.thrive-gdKchnn34ILGvF2CofgXCg==/oat/arm64/base.vdex (com.subconscious.thrive.common.cohorts.CohortManager$filterCohortsForSectionVariant$$inlined$map$1$2.emit+1546)
  #25  pc 0x00000000005bdb74  /apex/com.android.art/lib64/libart.so (nterp_helper+7540)
  #26  pc 0x0000000001da6dc2  /data/app/~~zS5ObOwx2IORomtK9QptyA==/com.subconscious.thrive-gdKchnn34ILGvF2CofgXCg==/oat/arm64/base.vdex (kotlinx.coroutines.flow.StateFlowImpl.collect+402)
  #27  pc 0x00000000005bcd54  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
  #28  pc 0x0000000001da6a38  /data/app/~~zS5ObOwx2IORomtK9QptyA==/com.subconscious.thrive-gdKchnn34ILGvF2CofgXCg==/oat/arm64/base.vdex (kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend+24)
  #29  pc 0x00000000005bcd54  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
  #30  pc 0x0000000001793acc  /data/app/~~zS5ObOwx2IORomtK9QptyA==/com.subconscious.thrive-gdKchnn34ILGvF2CofgXCg==/oat/arm64/base.vdex (kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith+16)
  #31  pc 0x0000000002033600  /memfd:jit-cache
```

### Can you reproduce the bug?

No

### Version

1.10.0

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android 13 and 12

### Build environment

Android Studio version: Iguana
Gradle version: 8.0.2

**Comment by rorbech** [comment] 2023-11-20 13:31
Hi @Shabinder. As you point out it seems related to #1577. It against look like some symbols are somehow stripped from the APK. I will close this issue to avoid duplicating discussions and we can reopen if we identify the root causes to be different.

**Closed by rorbech** 2023-11-20 13:31 UTC
Labels: O-Community, T-Bug, SDK-Use:Local, Encryption:Off, Frequency:Sometimes, Repro:No
