### ISSUE TITLE
Add step on CI to run sample app

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-kotlin#113] opened 2021-01-08 10:46 UTC
We need to make sure that CI runs the locally compiled binaries against the sample KMM app to avoid discrepancies between maven published binaries and locally built one. https://github.com/realm/realm-kotlin/issues/72#issuecomment-756346472

**Comment by rorbech** [comment] 2021-01-08 13:49
Duplicate of #79

**Closed by rorbech** 2021-01-08 13:49 UTC
